ignore:
 - "hmip_cli.py"
 - "hmip_generate_auth_token.py"
 - "versioneer.py"
 - "test.py"
 - "test_aio.py"
 - "setup.py"
 - "homematicip/_version.py"
 - "homematicip_cli.py"
 - "homematicip/base/constants.py"
