codecov:
  token: 45592767-5d72-4324-8470-aeda8ac812c1
ignore:
 - "hmip_cli.py"
 - "hmip_generate_auth_token.py"
 - "versioneer.py"
 - "test.py"
 - "test_aio.py"
 - "setup.py"
 - "homematicip/_version.py"
 - "homematicip_cli_async.py"
 - "homematicip/base/constants.py"
 - "homematicip/HomeMaticIPObject.py"