name: "Build docs"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_docs.txt
          pip install -r requirements_dev.txt
          pip install -e .
      - name: Build HTML
        run: |
          cd docs/
          make html
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html
